<html lang="en">

<head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">




</head>

<body>
    <p>Hello visitor!</p>

    <form method="post">

        <h1>Add a grocery item</h1>
        <label>Item name</label>
        <input type="text" name="foodName" placeholder="Delicious Food" required value="">
        <input type="submit" value="Add">
    </form>

    <a href="/">Back</a>

</body>
</html>